site:
  title: Clojurephant
  start_page: clojurephant::index.adoc
content:
  sources:
    - url: ../clojurephant
      branches: [HEAD]
      start_path: docs/
    - url: ../clojurephant-tooling
      branches: [HEAD]
      start_path: docs/
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental_ui
antora:
  extensions:
    - "@antora/lunr-extension"
