site:
  title: Clojurephant
  url: https://clojurephant.dev
  start_page: clojurephant::index.adoc
content:
  sources:
    - url: https://github.com/clojurephant/clojurephant.git
      branches: [main]
      start_path: docs/
    - url: https://github.com/clojurephant/clojurephant-tooling.git
      branches: [main]
      start_path: docs/
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental_ui
antora:
  extensions:
    - "@antora/lunr-extension"
