name: CD
on:
  push:
concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: false
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Antora build
        run: npx antora ./antora-playbook.yml
      - name: Disable Jekyll
        run: touch .nojekyll
      - name: Publish to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/site
          cname: clojurephant.dev
